#######################################################
server:
  port: 8080
  servlet:
    context-path: /

#######################################################
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/myproc
    username: yujin
    password: yujin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

#######################################################
jwt:
  token:
    secret: "yujin"

#######################################################

#######################################################